export const projects = [
  {
    title: 'Barber Lab',
    description: "Android and iOS Application. Custom app made in Flutter for a barber shop and its clients to manage appoint- ments.Published on the Google Play Store and iOS app store on December 2021",
      image: '/images/ios.png',
      tags: ['Flutter', 'Dart', 'FireBase', 'Node'],
    source: 'https://github.com/Demigod21/barber-lab',
    visit: 'https://apps.apple.com/it/app/barber-lab-by-lorenzo-sabatini/id1599707568',
    id: 0,
  },
  {
    title: 'HIIT Timer Pro',
    description:"Android Application. HIIT timer for workouts rich of functionalities such as background timer, custom workouts and saved workouts. Open-source and published on the Google Play Store on December 2020",
    image: '/images/timer.png',
    tags: ['Kotlin', 'Android', 'Android Studio'],
    source: 'https://github.com/Demigod21/HIIT-Timer-Pro',
    visit: 'https://play.google.com/store/apps/details?id=com.appdavide.roundtimer&gl=IT',
    id: 1,
  },
  {
    title: 'Personal Portfolio',
    description: "My personal portfolio, this site right here. Developed with NodeJS and React.",
      image: '/images/site.png',
      tags: ['React', 'NodeJS'],
    source: 'https://github.com/Demigod21/personal-website',
    visit: 'https://davidefalcone.com',
    id: 2,
  },
  {
    title: 'Code Generator',
    description: "Tool made with Apache Velocity to generate Java code for my daily work",
    image: '/images/velocity.png',
    tags: ['Apache Velocity', 'SpringBoot', 'JUnit'],
    source: 'https://github.com/Demigod21/OLVelocityCodeGenerator',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Shou Dao School',
    description: "Android application for a Martial Art School. Developed on Android Studio with Kotlin. Published on the Google Play Store on October 2019.",
    image: '/images/shou.png',
    tags: ['Kotlin', 'Android', 'Android Studio'],
    source: 'https://github.com/Demigod21/shou-dao-school',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'BlackJack',
    description: "Simple game of Blackjack realized with JavaFX made for Unipi. This game offers the possibility to split the hand. The most fun part to implement was the one about the 'Recommended Play' which is based on the Basic Strategy. ",
    image: '/images/blackjack.png',
    tags: ['Java', 'Javax'],
    source: 'https://github.com/Demigod21/Blackjack-Programmazione-Unipi',
    visit: 'https://play.google.com/store/apps/details?id=com.appDavide.shou_terzo',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Published my first Android app', },
  { year: 2020, text: 'Published my second Android app', },
  { year: 2021, text: 'Published my first iOS app', },
];