export const projects = [
  {
    title: 'Barber Lab',
    description: "Android and iOS Application. Custom app made in Flutter for a barber shop and its clients to manage appoint- ments.Published on the Google Play Store and iOS app store on December 2021",
      image: '/images/ios.png',
      tags: ['Flutter', 'Dart', 'FireBase', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'HIIT Timer Pro',
    description:"Android Application. HIIT timer for workouts rich of functionalities such as background timer, custom workouts and saved workouts. Open-source and published on the Google Play Store on December 2020",
    image: '/images/timer.png',
    tags: ['Kotlin', 'Android', 'Android Studio'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Personal Portfolio',
    description: "My personal portfolio, this site right here. Developed with NodeJS and React.",
      image: '/images/site.png',
      tags: ['React', 'NodeJS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Code Generator',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/velocity.png',
    tags: ['Apache Velocity', 'SpringBoot', 'JUnit'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Shou Dao School',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/shou.png',
    tags: ['Kotlin', 'Android', 'Android Studio'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'BlackJack',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/blackjack.png',
    tags: ['Java', 'Javax'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Published my first Android app', },
  { year: 2020, text: 'Published my second Android app', },
  { year: 2021, text: 'Published my first iOS app', },
];